name: Get Messages

on:
  schedule:
    - cron: '0 */6 * * *'  # This runs every 6 hours
  workflow_dispatch:

jobs:
  update-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run get_messages
      run: python get_messages.py
      env:
        FIRESTORE_TEXTKEY: ${{ secrets.FIRESTORE_TEXTKEY }}

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add messages.json
        git commit -m "Add messages.json" -a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}