name: Get Messages

on:
  schedule:
    - cron: '0 */6 * * *'  # This runs every 6 hours
  workflow_dispatch:

jobs:
  update-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run get_messages
      run: python -c 'from app import get_messages; get_messages()'